apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Udvozol az Cubix Webinar Demo!</title>
    </head>
    <body>
      <h1>Ez egy egyedi index.html fajl a mostani webinar-hoz keszult!</h1>
      <p>Ez az oldal egy Kubernetes Pod-bol szolgalodik ki.</p>
    </body>
    </html>
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
  namespace: default
  labels:
    app: nginx-demo
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: html-volume
      configMap:
        name: nginx-index
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx-demo
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
